### ISSUE TITLE
add support PP 0.30

### ISSUE THREAD

**Issue by neuromagus** [lumiknit/emacs-pragmatapro-ligatures#10]
Please, if you have a time, update emacs-pragmatapro-ligatures for support PragmataPro 0.30 version.

P.S. And I read your README ;)
>My little finger tired.... currently using custom keymap [alty](https://github.com/lumiknit/alty-key-map)

So, what are u use now? Because I fix emacs pinkie with swap keys:
Alt -> CTRL
WIN -> ALT
and for tiling WM move LWIN to RWIN... Dvorak... Custom layout etc...

**Comment by lumiknit** [comment]
Thanks to Fabrizio, it was upgraded for 0.830! (I was noticed 0.830 is updated by the PR 😆 )

> So, what are u use now?
I'm not using emacs lately. 🥲 As vscode is highly customizable, I think I don't need to use emacs more.... Also, I didn't change any modifier keys but only use alt and command key
