### ISSUE TITLE
Screenshot theme

### ISSUE THREAD

**Issue by rl-king** [lumiknit/emacs-pragmatapro-ligatures#5]
Thanks for this!

I was wondering, what theme are you using in the sample screenshot?

**Comment by lumiknit** [comment]
It's just my custom theme (very very highly influenced by the Haskell sample on PragmataPro page).
I uploaded it on [lumiknit/emacs-parchment-theme](https://github.com/lumiknit/emacs-parchment-theme) :)

**Comment by rl-king** [comment]
That's what I thought! I'd been looking for that one but gave up. I saw your screenshot and thought "there it is!" :) 

Thanks for the upload!
